diagnosis_task_cardiologist:
  description: >
    Create possible diagnoses based on the symptoms: {symptoms} for the user, looking at and cross-examining the past medical history. Provide a comprehensive analysis with detailed reasoning.
  expected_output: >
    A detailed list of possible diagnoses and the rationale for each, with supporting evidence from medical history.
  agent: cardiologist

diagnosis_task_pulmonologist:
  description: >
    Create possible diagnoses based on the symptoms: {symptoms} for the user, looking at and cross-examining the past medical history. Provide a comprehensive analysis with detailed reasoning.
  expected_output: >
    A detailed list of possible diagnoses and the rationale for each, with supporting evidence from medical history.
  agent: pulmonologist

diagnosis_task_neurologist:
  description: >
    Create possible diagnoses based on the symptoms: {symptoms} for the user, looking at and cross-examining the past medical history. Provide a comprehensive analysis with detailed reasoning.
  expected_output: >
    A detailed list of possible diagnoses and the rationale for each, with supporting evidence from medical history.
  agent: neurologist

diagnosis_decision:
  description: >
    Say which doctor should be alerted out of all the different doctors. Decide between all the diagnoses from the different agents to see which makes the most rational sense and is most likely to be true. Consider the analyses from the cardiologist, pulmonologist, and neurologist agents. Include metadata from the previous agents.
  expected_output: >
    The doctor that should be flagged and the final diagnosis that is most likely to be true
  agent: diagnosis_decider

diagnosis_dei_customizer:
  description: >
    Customizes the diagnosis given by the previous Diagnosis Decider agent to match the trends associated with their race and gender for that medical diagnosis. Restates which doctor to refer to.
  expected_output: >
    The final diagnosis that incorporates racial and gender concerns and important information based on the previous agent's diagnosis
  agent: diagnosis_dei

diagnosis_delivery:
  description: >
    Tell the patient which doctor they should talk to out of all the doctors. Present the final diagnosis to the patient in a supportive and empathetic manner, ensuring the reasoning is clear and accessible. Always refer to the patient with their name. Include metadata from the previous agents. Mention the racial considerations based on previous agents outputs. In your final response, make sure to relate back to the {symptoms}.
  expected_output: >
    The first word should be the doctor that should be flagged. The rest should be a comprehensive final diagnosis and rationale for the patient.
  agent: diagnosis_deliverer
